import './tab.js'
import './debug.js'

import './tabs/index.js'
import './tabs/bds.js'
import './tabs/stats.js'
import './tabs/console.js'
import './tabs/eval.js'
import './tabs/events.js'
import './tabs/runs.js'
import './tabs/properties.js'
import './tabs/timing.js'

import './lib/anchor.js'
import './lib/arrayavg.js'
import './lib/handle_resizer.js'
import './lib/inputhistory.js'
import './lib/iterator.js'
import './lib/jsonuninspector.js'
import './lib/misc.js'
import './lib/popup.js'
import './lib/prmctrl.js'
import './lib/resizelis.js'
import './lib/typedevt.js'
import './lib/units.js'
import './lib/uplotutil.js'
